---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-operatordev-io-v1beta1-deamonsetdev
  failurePolicy: Fail
  name: mdeamonsetdev.kb.io
  rules:
  - apiGroups:
    - apps.operatordev.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deamonsetdevs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-operatordev-io-v1beta1-deamonsetdev
  failurePolicy: Fail
  name: vdeamonsetdev.kb.io
  rules:
  - apiGroups:
    - apps.operatordev.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deamonsetdevs
  sideEffects: None
