# permissions for end users to edit deamonsetdevs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deamonsetdev-editor-role
rules:
- apiGroups:
  - apps.operatordev.io
  resources:
  - deamonsetdevs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.operatordev.io
  resources:
  - deamonsetdevs/status
  verbs:
  - get
