# permissions for end users to view deamonsetdevs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deamonsetdev-viewer-role
rules:
- apiGroups:
  - apps.operatordev.io
  resources:
  - deamonsetdevs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.operatordev.io
  resources:
  - deamonsetdevs/status
  verbs:
  - get
