---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.operatordev.io
  resources:
  - deamonsetdevs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.operatordev.io
  resources:
  - deamonsetdevs/finalizers
  verbs:
  - update
- apiGroups:
  - apps.operatordev.io
  resources:
  - deamonsetdevs/status
  verbs:
  - get
  - patch
  - update
